/**
 * Per-vertical listing attribute fields shown in the business portal editor.
 * Each VERTICALS slug has its own explicit field list (not shared family templates).
 */

import { VERTICALS, getVertical } from "@/config/verticals";

export type ListingFieldBoolean = {
  key: string;
  label: string;
  type: "boolean";
  help?: string;
};

export type ListingFieldEnum = {
  key: string;
  label: string;
  type: "enum";
  options: { value: string; label: string }[];
  help?: string;
};

export type ListingField = ListingFieldBoolean | ListingFieldEnum;

const NOISE_OPTIONS = [
  { value: "quiet", label: "Quiet" },
  { value: "moderate", label: "Moderate" },
  { value: "lively", label: "Lively" },
] as const;

const f = {
  parking: bool("parking", "Parking available"),
  wheelchair: bool("wheelchair", "Wheelchair accessible"),
  bookingRequired: bool("bookingRequired", "Booking required"),
  familyFriendly: bool("familyFriendly", "Family friendly"),
  petFriendly: bool("petFriendly", "Pet friendly"),
  kidsArea: bool("kidsArea", "Kids area"),
  seaView: bool("seaView", "Sea view"),
  outdoorSeating: bool("outdoorSeating", "Outdoor seating"),
  breakfast: bool("breakfast", "Breakfast"),
  lateNight: bool("lateNight", "Late night"),
  romantic: bool("romantic", "Romantic"),
  rainFriendly: bool("rainFriendly", "Good when it rains"),
  noiseLevel: enumField("noiseLevel", "Noise level", [...NOISE_OPTIONS]),
  emergencyCallOut: bool(
    "emergencyCallOut",
    "24hr / emergency call-out",
    "Available for urgent after-hours call-outs",
  ),
  afterHours: bool("afterHours", "After-hours service"),
  freeQuotes: bool("freeQuotes", "Free quotes"),
  insuredRegistered: bool("insuredRegistered", "Insured & registered"),
  residential: bool("residential", "Residential work"),
  commercial: bool("commercial", "Commercial work"),
  takeaway: bool("takeaway", "Takeaway"),
  delivery: bool("delivery", "Delivery"),
  reservations: bool("reservations", "Takes reservations"),
  walkIns: bool("walkIns", "Walk-ins welcome"),
  appointmentsOnly: bool("appointmentsOnly", "Appointments only"),
  medicalAidAccepted: bool("medicalAidAccepted", "Medical aid accepted"),
  homeVisits: bool("homeVisits", "Home / on-site visits"),
  atmOnSite: bool("atmOnSite", "ATM on site"),
  businessBanking: bool("businessBanking", "Business banking"),
  towingRoadside: bool("towingRoadside", "Towing / roadside assist"),
  dryCleaning: bool("dryCleaning", "Dry cleaning"),
  sameDayService: bool("sameDayService", "Same-day service"),
  selfService: bool("selfService", "Self-service"),
  convenienceStore: bool("convenienceStore", "Convenience store"),
  carWash: bool("carWash", "Car wash"),
  open24Hours: bool("open24Hours", "Open 24 hours"),
  toolHire: bool("toolHire", "Tool / equipment hire"),
  cutKeys: bool("cutKeys", "Key cutting"),
  flowerDelivery: bool("flowerDelivery", "Flower delivery"),
  aftercare: bool("aftercare", "Aftercare available"),
  mealsIncluded: bool("mealsIncluded", "Meals included"),
  classesAvailable: bool("classesAvailable", "Classes available"),
  personalTraining: bool("personalTraining", "Personal training"),
  returnsAccepted: bool("returnsAccepted", "Returns accepted"),
  giftWrapping: bool("giftWrapping", "Gift wrapping"),
  wifi: bool("wifi", "Wi‑Fi"),
  pool: bool("pool", "Pool"),
  airConditioning: bool("airConditioning", "Air conditioning"),
  ticketRequired: bool("ticketRequired", "Ticket / booking required"),
  guidedTours: bool("guidedTours", "Guided tours"),
  indoorPlay: bool("indoorPlay", "Indoor play"),
  outdoorPlay: bool("outdoorPlay", "Outdoor play"),
  cardPayments: bool("cardPayments", "Card payments"),
  onlineBooking: bool("onlineBooking", "Online booking"),
  contactLenses: bool("contactLenses", "Contact lenses"),
  eyeTests: bool("eyeTests", "Eye tests"),
  prescriptionDispensing: bool("prescriptionDispensing", "Prescription dispensing"),
  vaccinations: bool("vaccinations", "Vaccinations"),
  grooming: bool("grooming", "Pet grooming"),
  liveMusic: bool("liveMusic", "Live music"),
  cocktails: bool("cocktails", "Cocktails"),
  laptopFriendly: bool("laptopFriendly", "Laptop friendly"),
  veganOptions: bool("veganOptions", "Vegan options"),
  halalOptions: bool("halalOptions", "Halal options"),
  freshBread: bool("freshBread", "Fresh bread daily"),
  cakesCustom: bool("cakesCustom", "Custom cakes"),
  liquorSales: bool("liquorSales", "Liquor sales"),
  wineSelection: bool("wineSelection", "Wine selection"),
  organicProduce: bool("organicProduce", "Organic produce"),
  butcheryCounter: bool("butcheryCounter", "Butchery / deli counter"),
  colouring: bool("colouring", "Colouring / highlights"),
  mensCuts: bool("mensCuts", "Men's cuts"),
  nailServices: bool("nailServices", "Nail services"),
  massage: bool("massage", "Massage"),
  couplesTreatments: bool("couplesTreatments", "Couples treatments"),
} as const;

/** Readable phrases for embedding text (key → search-friendly wording). */
export const ATTRIBUTE_EMBEDDING_LABELS: Record<string, string> = {
  familyFriendly: "family friendly",
  romantic: "romantic",
  kidsArea: "kids area",
  seaView: "sea view",
  wheelchair: "wheelchair accessible",
  petFriendly: "pet friendly",
  breakfast: "breakfast",
  parking: "parking",
  outdoorSeating: "outdoor seating",
  bookingRequired: "booking required",
  rainFriendly: "rain friendly",
  lateNight: "late night",
  emergencyCallOut: "24 hour emergency call out",
  afterHours: "after hours service",
  freeQuotes: "free quotes",
  insuredRegistered: "insured and registered",
  residential: "residential",
  commercial: "commercial",
  takeaway: "takeaway",
  delivery: "delivery",
  reservations: "reservations",
  walkIns: "walk-ins welcome",
  appointmentsOnly: "appointments only",
  medicalAidAccepted: "medical aid accepted",
  homeVisits: "home visits",
  atmOnSite: "ATM on site",
  businessBanking: "business banking",
  towingRoadside: "towing roadside assist",
  dryCleaning: "dry cleaning",
  sameDayService: "same day service",
  selfService: "self service",
  convenienceStore: "convenience store",
  carWash: "car wash",
  open24Hours: "open 24 hours",
  toolHire: "tool hire",
  cutKeys: "key cutting",
  flowerDelivery: "flower delivery",
  aftercare: "aftercare",
  mealsIncluded: "meals included",
  classesAvailable: "classes available",
  personalTraining: "personal training",
  returnsAccepted: "returns accepted",
  giftWrapping: "gift wrapping",
  wifi: "wifi",
  pool: "pool",
  airConditioning: "air conditioning",
  ticketRequired: "ticket required",
  guidedTours: "guided tours",
  indoorPlay: "indoor play",
  outdoorPlay: "outdoor play",
  cardPayments: "card payments",
  onlineBooking: "online booking",
  contactLenses: "contact lenses",
  eyeTests: "eye tests",
  prescriptionDispensing: "prescription dispensing",
  vaccinations: "vaccinations",
  grooming: "pet grooming",
  liveMusic: "live music",
  cocktails: "cocktails",
  laptopFriendly: "laptop friendly",
  veganOptions: "vegan options",
  halalOptions: "halal options",
  freshBread: "fresh bread",
  cakesCustom: "custom cakes",
  liquorSales: "liquor sales",
  wineSelection: "wine selection",
  organicProduce: "organic produce",
  butcheryCounter: "butchery deli counter",
  colouring: "hair colouring",
  mensCuts: "mens cuts",
  nailServices: "nail services",
  massage: "massage",
  couplesTreatments: "couples treatments",
  noiseLevel: "noise level",
};

export const VERTICAL_LISTING_FIELDS: Record<string, readonly ListingField[]> = {
  restaurants: [
    f.outdoorSeating,
    f.takeaway,
    f.delivery,
    f.reservations,
    f.breakfast,
    f.kidsArea,
    f.familyFriendly,
    f.romantic,
    f.seaView,
    f.lateNight,
    f.veganOptions,
    f.halalOptions,
    f.parking,
    f.wheelchair,
    f.noiseLevel,
  ],
  takeaways: [
    f.takeaway,
    f.delivery,
    f.lateNight,
    f.open24Hours,
    f.veganOptions,
    f.halalOptions,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  cafes: [
    f.outdoorSeating,
    f.breakfast,
    f.laptopFriendly,
    f.takeaway,
    f.wifi,
    f.kidsArea,
    f.familyFriendly,
    f.veganOptions,
    f.parking,
    f.wheelchair,
    f.noiseLevel,
  ],
  bakeries: [
    f.freshBread,
    f.cakesCustom,
    f.takeaway,
    f.breakfast,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  bars: [
    f.outdoorSeating,
    f.liveMusic,
    f.cocktails,
    f.lateNight,
    f.romantic,
    f.seaView,
    f.parking,
    f.wheelchair,
    f.noiseLevel,
  ],
  grocery: [
    f.open24Hours,
    f.organicProduce,
    f.butcheryCounter,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  butchers: [
    f.butcheryCounter,
    f.organicProduce,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  liquor: [
    f.liquorSales,
    f.wineSelection,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  "hair-salons": [
    f.colouring,
    f.walkIns,
    f.appointmentsOnly,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
    f.wheelchair,
  ],
  barbershops: [
    f.mensCuts,
    f.walkIns,
    f.appointmentsOnly,
    f.bookingRequired,
    f.parking,
    f.wheelchair,
  ],
  beauticians: [
    f.nailServices,
    f.walkIns,
    f.appointmentsOnly,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
    f.wheelchair,
  ],
  spas: [
    f.massage,
    f.couplesTreatments,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
    f.wheelchair,
    f.seaView,
  ],
  doctors: [
    f.walkIns,
    f.appointmentsOnly,
    f.medicalAidAccepted,
    f.homeVisits,
    f.emergencyCallOut,
    f.afterHours,
    f.parking,
    f.wheelchair,
    f.onlineBooking,
  ],
  dentists: [
    f.walkIns,
    f.appointmentsOnly,
    f.medicalAidAccepted,
    f.emergencyCallOut,
    f.afterHours,
    f.parking,
    f.wheelchair,
    f.onlineBooking,
  ],
  pharmacies: [
    f.prescriptionDispensing,
    f.open24Hours,
    f.afterHours,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  optometrists: [
    f.eyeTests,
    f.contactLenses,
    f.appointmentsOnly,
    f.walkIns,
    f.medicalAidAccepted,
    f.parking,
    f.wheelchair,
    f.onlineBooking,
  ],
  vets: [
    f.emergencyCallOut,
    f.afterHours,
    f.walkIns,
    f.appointmentsOnly,
    f.homeVisits,
    f.vaccinations,
    f.grooming,
    f.parking,
    f.wheelchair,
  ],
  laundry: [
    f.selfService,
    f.dryCleaning,
    f.sameDayService,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  banks: [
    f.atmOnSite,
    f.businessBanking,
    f.wheelchair,
    f.parking,
    f.cardPayments,
  ],
  petrol: [
    f.open24Hours,
    f.convenienceStore,
    f.carWash,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  hardware: [
    f.toolHire,
    f.cutKeys,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  florists: [
    f.flowerDelivery,
    f.sameDayService,
    f.cardPayments,
    f.parking,
    f.wheelchair,
  ],
  childcare: [
    f.aftercare,
    f.mealsIncluded,
    f.outdoorPlay,
    f.indoorPlay,
    f.parking,
    f.wheelchair,
  ],
  plumbers: [
    f.emergencyCallOut,
    f.afterHours,
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
  ],
  electricians: [
    f.emergencyCallOut,
    f.afterHours,
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
  ],
  locksmiths: [
    f.emergencyCallOut,
    f.afterHours,
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.bookingRequired,
    f.parking,
  ],
  handyman: [
    f.emergencyCallOut,
    f.afterHours,
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
  ],
  hvac: [
    f.emergencyCallOut,
    f.afterHours,
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
  ],
  property: [
    f.parking,
    f.wheelchair,
    f.wifi,
    f.appointmentsOnly,
    f.onlineBooking,
    f.cardPayments,
  ],
  security: [
    f.emergencyCallOut,
    f.afterHours,
    f.open24Hours,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.freeQuotes,
    f.parking,
  ],
  telecom: [
    f.residential,
    f.commercial,
    f.freeQuotes,
    f.sameDayService,
    f.onlineBooking,
    f.parking,
  ],
  movers: [
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.sameDayService,
    f.bookingRequired,
    f.parking,
  ],
  cleaning: [
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.sameDayService,
    f.bookingRequired,
    f.onlineBooking,
    f.parking,
  ],
  "pool-services": [
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.sameDayService,
    f.bookingRequired,
    f.parking,
  ],
  landscaping: [
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.bookingRequired,
    f.parking,
  ],
  "pest-control": [
    f.emergencyCallOut,
    f.afterHours,
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.sameDayService,
    f.bookingRequired,
    f.parking,
  ],
  contractors: [
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.bookingRequired,
    f.parking,
  ],
  legal: [
    f.appointmentsOnly,
    f.onlineBooking,
    f.parking,
    f.wheelchair,
    f.wifi,
  ],
  accountants: [
    f.appointmentsOnly,
    f.onlineBooking,
    f.parking,
    f.wheelchair,
    f.wifi,
  ],
  fabrication: [
    f.emergencyCallOut,
    f.afterHours,
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.walkIns,
    f.bookingRequired,
    f.parking,
  ],
  automotive: [
    f.towingRoadside,
    f.emergencyCallOut,
    f.afterHours,
    f.walkIns,
    f.bookingRequired,
    f.carWash,
    f.parking,
    f.wheelchair,
  ],
  fitness: [
    f.classesAvailable,
    f.personalTraining,
    f.parking,
    f.wheelchair,
    f.wifi,
    f.familyFriendly,
    f.onlineBooking,
  ],
  shopping: [
    f.returnsAccepted,
    f.giftWrapping,
    f.parking,
    f.wheelchair,
    f.cardPayments,
    f.familyFriendly,
  ],
  electronics: [
    f.returnsAccepted,
    f.parking,
    f.wheelchair,
    f.cardPayments,
    f.wifi,
  ],
  "sporting-goods": [
    f.returnsAccepted,
    f.parking,
    f.wheelchair,
    f.cardPayments,
    f.familyFriendly,
  ],
  furniture: [
    f.returnsAccepted,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  "surf-shops": [
    f.returnsAccepted,
    f.parking,
    f.cardPayments,
    f.familyFriendly,
  ],
  tyres: [
    f.parking,
    f.wheelchair,
    f.cardPayments,
    f.sameDayService,
  ],
  "panel-beaters": [
    f.towingRoadside,
    f.emergencyCallOut,
    f.afterHours,
    f.walkIns,
    f.bookingRequired,
    f.parking,
    f.wheelchair,
  ],
  "pet-shops": [
    f.grooming,
    f.parking,
    f.wheelchair,
    f.cardPayments,
    f.familyFriendly,
  ],
  "baby-toys": [
    f.returnsAccepted,
    f.parking,
    f.wheelchair,
    f.cardPayments,
    f.familyFriendly,
    f.giftWrapping,
  ],
  stationery: [
    f.returnsAccepted,
    f.parking,
    f.wheelchair,
    f.cardPayments,
  ],
  "bike-shops": [
    f.returnsAccepted,
    f.parking,
    f.cardPayments,
    f.sameDayService,
  ],
  marine: [
    f.returnsAccepted,
    f.parking,
    f.cardPayments,
  ],
  "music-instruments": [
    f.returnsAccepted,
    f.parking,
    f.cardPayments,
    f.sameDayService,
    f.walkIns,
  ],
  physio: [
    f.appointmentsOnly,
    f.medicalAidAccepted,
    f.parking,
    f.wheelchair,
    f.onlineBooking,
  ],
  travel: [f.parking, f.cardPayments, f.onlineBooking, f.wifi],
  "car-rental": [f.parking, f.cardPayments, f.open24Hours],
  entertainment: [
    f.familyFriendly,
    f.kidsArea,
    f.parking,
    f.ticketRequired,
    f.cardPayments,
  ],
  clothing: [
    f.returnsAccepted,
    f.parking,
    f.cardPayments,
    f.familyFriendly,
  ],
  footwear: [f.returnsAccepted, f.parking, f.cardPayments],
  jewellery: [f.returnsAccepted, f.parking, f.cardPayments],
  insurance: [f.parking, f.appointmentsOnly, f.wifi],
  "car-dealerships": [f.parking, f.cardPayments, f.wifi],
  solar: [
    f.freeQuotes,
    f.insuredRegistered,
    f.residential,
    f.commercial,
    f.parking,
  ],
  hospitals: [
    f.emergencyCallOut,
    f.open24Hours,
    f.parking,
    f.wheelchair,
    f.medicalAidAccepted,
  ],
  photography: [f.parking, f.cardPayments, f.onlineBooking],
  events: [f.parking, f.familyFriendly, f.bookingRequired, f.wifi],
  golf: [f.parking, f.familyFriendly, f.cardPayments, f.bookingRequired],
  "garden-centres": [f.parking, f.cardPayments, f.familyFriendly],
  "blinds-flooring": [f.parking, f.cardPayments, f.freeQuotes],
  paint: [f.parking, f.cardPayments],
  "appliance-repair": [
    f.sameDayService,
    f.afterHours,
    f.parking,
    f.cardPayments,
  ],
  "auto-parts": [f.parking, f.cardPayments, f.sameDayService],
  tattoo: [f.appointmentsOnly, f.parking, f.cardPayments, f.walkIns],
  "pet-grooming": [
    f.grooming,
    f.parking,
    f.cardPayments,
    f.appointmentsOnly,
  ],
  storage: [f.parking, f.cardPayments, f.open24Hours],
  "skip-hire": [f.parking, f.cardPayments, f.sameDayService],
  architects: [f.parking, f.freeQuotes, f.appointmentsOnly],
  books: [f.returnsAccepted, f.parking, f.cardPayments, f.wifi],
  funeral: [f.parking, f.wheelchair],
  "shoe-repair": [f.parking, f.cardPayments, f.sameDayService, f.cutKeys],
  employment: [f.parking, f.appointmentsOnly, f.wifi],
  "debt-collection": [f.parking, f.appointmentsOnly],
  "farm-supplies": [f.parking, f.cardPayments],
  hotels: [
    f.parking,
    f.breakfast,
    f.seaView,
    f.familyFriendly,
    f.petFriendly,
    f.wifi,
    f.pool,
    f.airConditioning,
    f.wheelchair,
    f.bookingRequired,
  ],
  attractions: [
    f.familyFriendly,
    f.kidsArea,
    f.seaView,
    f.rainFriendly,
    f.ticketRequired,
    f.guidedTours,
    f.parking,
    f.wheelchair,
    f.petFriendly,
  ],
  family: [
    f.familyFriendly,
    f.kidsArea,
    f.indoorPlay,
    f.outdoorPlay,
    f.rainFriendly,
    f.parking,
    f.wheelchair,
    f.petFriendly,
  ],
};

function bool(key: string, label: string, help?: string): ListingFieldBoolean {
  return help ? { key, label, type: "boolean", help } : { key, label, type: "boolean" };
}

function enumField(
  key: string,
  label: string,
  options: { value: string; label: string }[],
  help?: string,
): ListingFieldEnum {
  return help
    ? { key, label, type: "enum", options, help }
    : { key, label, type: "enum", options };
}

/** Display label for an attribute key (portal / detail UI). */
export function attributeDisplayLabel(key: string): string {
  for (const fields of Object.values(VERTICAL_LISTING_FIELDS)) {
    const field = fields.find((f) => f.key === key);
    if (field) return field.label;
  }
  const embed = ATTRIBUTE_EMBEDDING_LABELS[key];
  if (embed) {
    return embed.charAt(0).toUpperCase() + embed.slice(1);
  }
  return key;
}

/** Fields for a vertical slug; empty array if unknown. */
export function getListingFieldsForVertical(slug: string): readonly ListingField[] {
  return VERTICAL_LISTING_FIELDS[slug] ?? [];
}

/** All known attribute keys across every vertical (for schema / docs). */
export function allListingAttributeKeys(): string[] {
  const keys = new Set<string>();
  for (const fields of Object.values(VERTICAL_LISTING_FIELDS)) {
    for (const field of fields) keys.add(field.key);
  }
  return [...keys].sort();
}

/** Ensure every VERTICALS slug has a field list (dev sanity). */
export function assertVerticalListingFieldsComplete(): void {
  for (const v of VERTICALS) {
    if (!VERTICAL_LISTING_FIELDS[v.slug]?.length) {
      throw new Error(`Missing listing fields for vertical: ${v.slug}`);
    }
  }
}

export function listingVerticalLabel(slug: string): string {
  return getVertical(slug)?.label ?? slug;
}
