/**
 * Bootstrap local development against Supabase running in Docker.
 *
 * Prerequisites:
 *   - Docker Desktop running (`docker info` succeeds)
 *   - Node.js 20+ / npm
 *   - OPENAI_API_KEY in the environment (or already in .env.local)
 *
 * Usage (from repo root):
 *   npm run setup:local
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const ENV_PATH = join(ROOT, ".env.local");

function run(command, args, opts = {}) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    encoding: "utf8",
    stdio: opts.stdio ?? "inherit",
    shell: process.platform === "win32",
    env: { ...process.env, ...opts.env },
  });
  if (result.status !== 0) {
    const detail = result.stderr?.trim() || result.stdout?.trim() || "";
    throw new Error(
      `Command failed (${result.status}): ${command} ${args.join(" ")}${
        detail ? `\n${detail}` : ""
      }`,
    );
  }
  return result;
}

function runCapture(command, args) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    const detail = (result.stderr || result.stdout || "").trim();
    throw new Error(
      `Command failed (${result.status}): ${command} ${args.join(" ")}${
        detail ? `\n${detail}` : ""
      }`,
    );
  }
  return (result.stdout || "").trim();
}

function parseEnvFile(contents) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of contents.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function formatEnv(vars) {
  const lines = [
    "# Generated by `npm run setup:local` — do not commit.",
    "# Re-run the script to refresh Supabase local keys.",
    "",
  ];
  for (const [key, value] of Object.entries(vars)) {
    if (value === undefined || value === null || value === "") continue;
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  return lines.join("\n");
}

function assertDocker() {
  console.log("→ Checking Docker...");
  const result = spawnSync("docker", ["info"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    throw new Error(
      "Docker is not available or the engine is not running.\n" +
        "On Windows: start Docker Desktop, wait until it is healthy, then re-run.\n" +
        "First-time Windows setup: run scripts/windows/Install-Prereqs.ps1 as Administrator.",
    );
  }
  console.log("  Docker OK");
}

function installDeps() {
  console.log("→ Installing npm dependencies...");
  run("npm", ["install"]);
}

function startSupabase() {
  console.log("→ Starting local Supabase (Docker)...");
  run("npx", ["supabase", "start"]);
}

/**
 * @returns {{
 *   apiUrl: string,
 *   anonKey: string,
 *   serviceRoleKey: string,
 *   dbUrl: string,
 *   studioUrl?: string,
 * }}
 */
function readSupabaseStatus() {
  console.log("→ Reading Supabase status...");
  const raw = runCapture("npx", ["supabase", "status", "-o", "json"]);
  const status = JSON.parse(raw);

  const apiUrl =
    status.API_URL ||
    status.api_url ||
    status.APIUrl ||
    "http://127.0.0.1:55421";
  const anonKey = status.ANON_KEY || status.anon_key;
  const serviceRoleKey = status.SERVICE_ROLE_KEY || status.service_role_key;
  const dbUrl =
    status.DB_URL ||
    status.db_url ||
    "postgresql://postgres:postgres@127.0.0.1:55422/postgres";
  const studioUrl = status.STUDIO_URL || status.studio_url;

  if (!anonKey || !serviceRoleKey) {
    throw new Error(
      "Could not read anon/service_role keys from `supabase status -o json`.\n" +
        `Got keys: ${Object.keys(status).join(", ")}`,
    );
  }

  return { apiUrl, anonKey, serviceRoleKey, dbUrl, studioUrl };
}

function writeEnvLocal(supabase) {
  console.log("→ Writing .env.local...");

  /** @type {Record<string, string>} */
  const existing = existsSync(ENV_PATH)
    ? parseEnvFile(readFileSync(ENV_PATH, "utf8"))
    : {};

  const openai =
    process.env.OPENAI_API_KEY?.trim() ||
    existing.OPENAI_API_KEY?.trim() ||
    "";

  if (!openai || openai.includes("your-openai")) {
    throw new Error(
      "OPENAI_API_KEY is required.\n" +
        (process.platform === "win32"
          ? 'In PowerShell:  $env:OPENAI_API_KEY = "sk-..."\n'
          : 'In bash:        export OPENAI_API_KEY=sk-...\n') +
        "Then re-run: npm run setup:local",
    );
  }

  /** @type {Record<string, string>} */
  const next = {
    NEXT_PUBLIC_SITE_URL: "http://localhost:3000",
    NEXT_PUBLIC_SUPABASE_URL: supabase.apiUrl,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: supabase.anonKey,
    SUPABASE_SERVICE_ROLE_KEY: supabase.serviceRoleKey,
    SUPABASE_DB_URL: supabase.dbUrl,
    OPENAI_API_KEY: openai,
    OPENAI_MODEL: existing.OPENAI_MODEL || "gpt-4.1-mini",
    OPENAI_EMBEDDING_MODEL:
      existing.OPENAI_EMBEDDING_MODEL || "text-embedding-3-small",
    OPENAI_EMBEDDING_DIMENSIONS: existing.OPENAI_EMBEDDING_DIMENSIONS || "1536",
    ENABLE_DEMO_LOGIN: existing.ENABLE_DEMO_LOGIN || "true",
    NEXT_PUBLIC_ENABLE_DEMO_LOGIN:
      existing.NEXT_PUBLIC_ENABLE_DEMO_LOGIN || "true",
    DEMO_LOGIN_PASSWORD:
      existing.DEMO_LOGIN_PASSWORD || "AskBallitoDemo!2026",
  };

  // Preserve optional keys if the user already set them.
  for (const key of [
    "GOOGLE_PLACES_API_KEY",
    "GOOGLE_WEATHER_API_KEY",
    "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY",
    "UPSTASH_REDIS_REST_URL",
    "UPSTASH_REDIS_REST_TOKEN",
    "RESEND_API_KEY",
    "RESEND_FROM_EMAIL",
    "NEXT_PUBLIC_POSTHOG_KEY",
    "NEXT_PUBLIC_POSTHOG_HOST",
    "NEXT_PUBLIC_SENTRY_DSN",
    "CRON_SECRET",
  ]) {
    const fromEnv = process.env[key]?.trim();
    const fromFile = existing[key]?.trim();
    const value = fromEnv || fromFile;
    if (value) next[key] = value;
  }

  writeFileSync(ENV_PATH, formatEnv(next), "utf8");
  console.log(`  Wrote ${ENV_PATH}`);
}

function migrate() {
  console.log("→ Applying SQL migrations...");
  run("npm", ["run", "migrate"]);
}

function seedDemoAccounts() {
  console.log("→ Seeding demo accounts...");
  try {
    run("npm", ["run", "seed:demo-accounts"]);
  } catch (err) {
    console.warn(
      "  Demo account seed failed (app still runs). You can retry with:\n" +
        "  npm run seed:demo-accounts\n" +
        `  ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

function main() {
  console.log("Ask Ballito — local setup\n");
  assertDocker();
  installDeps();
  startSupabase();
  const supabase = readSupabaseStatus();
  writeEnvLocal(supabase);
  migrate();
  seedDemoAccounts();

  console.log(`
Setup complete.

  App:     http://localhost:3000  (npm run dev)
  Studio:  ${supabase.studioUrl || "http://127.0.0.1:55423"}
  API:     ${supabase.apiUrl}
  DB:      ${supabase.dbUrl}

Demo login (local):
  admin@demo.askballito.local / AskBallitoDemo!2026
  business@demo.askballito.local / AskBallitoDemo!2026
  user@demo.askballito.local / AskBallitoDemo!2026

Optional — ingest Ballito businesses (needs GOOGLE_PLACES_API_KEY):
  npm run ingest -- ballito
  npm run enrich -- ballito
`);
}

try {
  main();
} catch (err) {
  console.error(`\nSetup failed:\n${err instanceof Error ? err.message : err}`);
  process.exit(1);
}
